# Generated by Django 6.0.6 on 2026-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='eraser_lines',
            field=models.JSONField(blank=True, help_text='Stores eraser line data', null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='pen_lines',
            field=models.JSONField(blank=True, help_text='Stores pen line data', null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='polygon_points',
            field=models.JSONField(blank=True, help_text='Stores an array of x, y coordinates', null=True),
        ),
    ]
